In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [3]:
df = pd.read_csv('../result/result_full_NARTI_dentate.csv')

In [4]:
df

,Unnamed: 0,ISO score,GED score,IM score,ARI,GRI,PDT score,method,type,data,source
0,0,0,0.4,0.349111,0.671077,0.30482,0.638067,mean,UMI,dentate,dyno
1,1,0,0.4,0.349111,0.671077,0.30482,0.638067,modified_mean,UMI,dentate,dyno
2,2,0,0.4,0.349111,0.671077,0.30482,0.638067,map,UMI,dentate,dyno
3,3,0,0.4,0.349111,0.671077,0.30482,0.638067,modified_map,UMI,dentate,dyno
4,4,0,0.4,0.349111,0.671077,0.30482,0.638067,mean,UMI,dentate,dyno
5,5,0,0.4,0.349111,0.671077,0.30482,0.638067,modified_mean,UMI,dentate,dyno
6,6,0,0.4,0.349111,0.671077,0.30482,0.638067,map,UMI,dentate,dyno
7,7,0,0.4,0.349111,0.671077,0.30482,0.638067,modified_map,UMI,dentate,dyno
8,8,0,0.4,0.349111,0.671077,0.30482,0.638067,mean,UMI,dentate,dyno
9,9,0,0.4,0.349111,0.671077,0.30482,0.638067,modified_mean,UMI,dentate,dyno
10,10,0,0.4,0.349111,0.671077,0.30482,0.638067,map,UMI,dentate,dyno
11,11,0,0.4,0.349111,0.671077,0.30482,0.638067,modified_map,UMI,dentate,dyno
12,12,0,0.4,0.349111,0.671077,0.30482,0.638067,mean,UMI,dentate,dyno
13,13,0,0.4,0.349111,0.671077,0.30482,0.638067,modified_mean,UMI,dentate,dyno
14,14,0,0.4,0.349111,0.671077,0.30482,0.638067,map,UMI,dentate,dyno
15,15,0,0.4,0.349111,0.671077,0.30482,0.638067,modified_map,UMI,dentate,dyno
16,16,0,0.4,0.349111,0.671077,0.30482,0.638067,mean,UMI,dentate,dyno
17,17,0,0.4,0.349111,0.671077,0.30482,0.638067,modified_mean,UMI,dentate,dyno
18,18,0,0.4,0.349111,0.671077,0.30482,0.638067,map,UMI,dentate,dyno
19,19,0,0.4,0.349111,0.671077,0.30482,0.638067,modified_map,UMI,dentate,dyno